### ISSUE TITLE
Help a newbie 

### ISSUE THREAD

**Issue by vmamore** [luansantosti/recoil-cart#2]
Hey @luansantosti, how are you?

First I want to thank you for the repo, I'm learning react and this project gave me the first contact to recoil. I'm pretty amazed about the possibilities that I can do with that! 💯 

In my clone repo I implemented the feature to remove a product from the cart and it worked, now I want to implement an option to update the product with an input from a value that the user typed but I can't figure out how to get the value from the input, could you make an example or give me any tips on how to do that?

Thanks!

**Comment by luansantosti** [comment]
Hey @vmamore, first of all, I'm really glad that this repo could help you to understand better how recoil works, regarding the new feature of removing a product, you can send a PR any time if you want. o/

About the update, you will need two things, an state (useState) to save the value where the user will edit, and also the id of the product to update it on your list. For example:
`const [value, setValue] = useState(product.title);` // here you need to get the value from the product that you are rendering;

Then, in your input you will have something like this:
`<input value={value} onChange={(e) => setValue(e.target.value)}/>`

After doing this, probably you will need a button with a function to update your product, right? in this function, you have to pass the `id` of the product to know which product should be updated on the list. 

You can dm me on twitter if you need any help to accomplish this. @luansantosti o/
